#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        dlink_dsl500t_csrf:
            enable: true
            category: ["Exploits", "Router"]
            name: "D-Link DSL500T CSRF"
            description: "Attempts to change the password on a D-Link DSL500T router."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
