#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
# More info: http://www.exploit-db.com/exploits/18509/
#
beef:
    module:
        Dlink_dcs_series_csrf:
            enable: true
            category: ["Exploits", "Camera"]
            name: "Dlink DCS series CSRF"
            description: "Attempts to change the password on a Dlink DCS series camera."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
