#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        detect_default_browser:
            enable: true
            category: "Browser"
            name: "Detect Default Browser"
            description: "This module detects which browser is configured as the default web browser."
            authors: ["unsticky", "bcoles"]
            target:
                 working: ["IE"]
                 not_working: ["All"]
