#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        zenoss_add_user_csrf:
            enable: true
            category: "Exploits"
            name: "Zenoss 3.x Add User CSRF"
            description: "Attempts to add a user to a Zenoss Core 3.x server."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
