#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        ruby_nntpd_cmd_exec:
            enable: true
            category: "Exploits"
            name: "ruby-nntpd Command Execution"
            description: "This module uses the 'eval' verb in ruby-nntpd 0.01dev (default port 1119) to execute operating system commands.<br /><br />The target address can be on the hooked browser's subnet which is potentially not directly accessible from the Internet.<br/><br/>The results of the commands are not returned to BeEF."
            authors: ["bcoles"]
            target:
                working: ["FF", "C"]
                not_working: ["IE"]
