#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        cisco_collaboration_server_5_xss:
            enable: true
            category: ["Exploits", "XSS"]
            name: "Cisco Collaboration Server 5 XSS"
            description: "Attempts to hook Cisco Collaboration Server 5 using XSS.<br/>For more information see: http://www.exploit-db.com/exploits/11403/"
            authors: ["bcoles", "s4squatch"]
            target:
                unknown: ["ALL"]
