#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
#   phonegap
#
beef:
    module:
        phonegap_file_upload:
            enable: true
            category: "Phonegap"
            name: "Upload File"
            description: "Upload files from device to a server of your choice."
            authors: ["mh"]
            target:
                working: ["All"]
