#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        send_gvoice_sms:
            enable: true
            category: "Chrome Extensions"
            name: "Send Gvoice SMS"
            description: "Send a text message (SMS) through the Google Voice account of the victim, if she's logged in to Google."
            authors: ["Kos", "antisnatchor"]
            target:
                user_notify: ["C"]
                not_working: ["ALL"]
