#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        dlink_dir_615_csrf:
            enable: true
            category: ["Exploits", "Router"]
            name: "D-Link DIR-615 Password Wipe"
            description: "Attempts to enable remote administration on port 8080 and change the admin password on a D-Link DIR-615 router."
            authors: ["antisnatchor", "n0x00"]
            target:
                working: ["ALL"]
