#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        get_system_info:
            enable: true
            category: "Host"
            name: "Get System Info"
            description: "This module will retrieve basic information about the host system using an unsigned Java Applet. <br/><br/>The details will include:<br/> <ul><li> - Operating system details</li><li> - Java VM details</li><li> - NIC names and IP</li><li> - Number of processors</li><li> - Amount of memory</li><li> - Screen display modes</li></ul>"
            authors: ["bcoles", "antisnatchor"]
            target:
                not_working:
                    ALL:
                        os: ["iOS", "Macintosh"]
                working: ["O", "FF", "S", "IE"]
                user_notify: ["C"]
