#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
#   Phonegap_globalization_status
#
beef:
    module:
        phonegap_globalization_status:
            enable: true
            category: "Phonegap"
            name: "Globalization Status"
            description: "Examine device local settings"
            authors: ["staregate"]
            target:
                working: ["All"]
