#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        test_cors_request:
            enable: true
            category: "Debug"
            name: "Test CORS Request"
            description: "Test the beef.net.cors.request function by retrieving a URL."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
                not_working:
                    IE:
                        min_ver: 6
                        max_ver: 7
                    O:
                        min_ver: 1
                        max_ver: 11
                    C:
                        min_ver: 1
                        max_ver: 2
                    S:
                        min_ver: 1
                        max_ver: 3
