#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
################################################################################
# For more information see: http://itsecuritysolutions.org/2012-07-30-zenoss-3.2.1-multiple-security-vulnerabilities/
################################################################################
beef:
    module:
        zenoss_command_execution:
            enable: true
            category: "Exploits"
            name: "Zenoss 3.x Command Execution"
            description: "Attempts to get a reverse shell on a Zenoss 3.x server. Valid credentials are required."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
