#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    extension:
        customhook:
            enable: false
            name: 'Custom Hook Point with iFrame Impersonation'
            customhook_path: "/yougotchipmunked"
            customhook_target: "http://www.chipmunks.com"
            customhook_title: "Alvin and the Chipmunks.."

