#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        virgin_superhub_csrf:
            enable: true
            category: ["Exploits", "Router"]
            name: "Virgin Superhub CSRF"
            description: "Attempts to enable remote administration, disable the firewall, and change the admin password on a Virgin Superhub router."
            authors: ["bcoles", "n0x00"]
            target:
                working: ["ALL"]
