#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        grab_google_contacts:
            enable: true
            category: "Chrome Extensions"
            name: "Grab Google Contacts"
            description: "Attempt to grab the contacts of the currently logged in Google account, exploiting the export to CSV feature."
            authors: ["Kos", "antisnatchor"]
            target:
                working: ["C"]
                not_working: ["All"]
