#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        rickroll:
            enable: true
            category: ["Browser", "Hooked Domain"]
            name: "Redirect Browser (Rickroll)"
            description: "Overwrite the body of the page the victim is on with a full screen Rickroll."
            authors: ["Yori Kvitchko"]
            target:
                user_notify: ['ALL']
