#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        get_visited_urls:
            enable: true
            category: "Browser"
            name: "Get Visited URLs"
            description: "This module will detect whether or not the hooked browser has visited the specified URL(s)"
            authors: ["passbe"]
            target:
                working:
                    IE:
                        min_ver: 6
                        max_ver: 7
                    FF:
                        min_ver: 3
                        max_ver: 3
                    C:
                        min_ver: 1
                        max_ver: 5
                    S:
                        min_ver: 3
                        max_ver: 3
                    O:
                        min_ver: 1
                        max_ver: 10
                not_working: ["All"]
