#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        Huawei_smartax_mt880_csrf:
            enable: true
            category: ["Exploits", "Router"]
            name: "Huawei SmartAX MT880 CSRF"
            description: "Attempts to add an administrator account on a Huawei SmartAX MT880 router."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
