#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        activex_command_execution:
            enable: true
            category: ["Exploits", "Local Host"]
            name: "ActiveX Command Execution"
            description: "Execute arbitrary commands using the \"WSCRIPT.Shell\" object. The command response is not returned to BeEF.<br><br>The browser must have \"Initialize and script ActiveX controls not marked as safe for scripting\" enabled."
            authors: ["bcoles"]
            target:
                user_notify: ["IE"]
                not_working: ["ALL"]
