#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        link_rewrite:
            enable: true
            category: ["Browser", "Hooked Domain"]
            name: "Replace HREFs"
            description: "This module will rewrite all the href attributes of all matched links."
            authors: ["passbe"]
            target:
                working: ["ALL"]
