#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        iphone_tel:
            enable: true
            category: "Host"
            name: "Make Telephone Call"
            description: "This module will force the browser to attempt a telephone call in iOS. It will exploit the insecure handling of URL schemes in iOS.<br><br>The protocol handler used will be: tel"
            authors: ["xntrik", "Nitesh Dhanjani"]
            target:
                user_notify:
                    S:
                        os: ["iOS"]
                not_working:
                    ALL:
                        os: ["All"]
