#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        inter_protocol_posix_bindshell:
            enable: true
            category: "IPEC"
            name: "Bindshell (POSIX)"
            description: "Using Inter-protocol Exploitation/Communication (IPEC) the hooked browser will send commands to a listening POSIX shell bound on the target specified in the 'Target Address' input field. <br><br>The target address can be on the hooked browser's subnet which is potentially not directly accessible from the Internet."
            authors: ["bcoles", "wade"]
            target:
                working: ["FF"]
                not_working: ["C", "S", "O", "IE"]
