#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        asmax_ar804gu_cmd_exec:
            enable: true
            category: ["Exploits", "Router"]
            name: "Asmax AR-804gu Command Execution"
            description: "Attempts to execute arbitrary commands on a Asmax AR-804gu (OSVDB# 54895).<br/>For more information see, http://www.securitum.pl/dh/asmax-ar-804-gu-compromise"
            authors: ["bcoles", "Michal Sajdak"]
            target:
                working: ["ALL"]
