#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        link_rewrite_sslstrip:
            enable: true
            category: ["Browser", "Hooked Domain"]
            name: "Replace HREFs (HTTPS)"
            description: "This module will rewrite all the href attributes of HTTPS links to use HTTP instead of HTTPS. Links relative to the web root are not rewritten."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
