#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        windows_mail_client_dos:
            enable: true
            category: ["Exploits", "Local Host"]
            name: "Windows Mail Client DoS"
            description: "This module exploits an unhandled exception in Windows Mail to crash the client remotely.<br /><br />Windows Mail is launched and then crashed if it is not already open. It comes installed by default on Windows Vista (but it's also vulnerable on Windows 7 SP2).<br /><br />The protocol handler used will be: nntp."
            authors: ["bcoles"]
            target:
                user_notify: ["FF", "S"]
                not_working: ["All"]
