#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        qnx_qconn_command_execution:
            enable: true
            category: "Exploits"
            name: "QNX QCONN Command Execution"
            description: "This module exploits a vulnerability in the qconn component of QNX Neutrino which can be abused to allow unauthenticated users to execute arbitrary commands under the context of the 'root' user.<br/><br/>The results of the commands are not returned to BeEF."
            authors: ["bcoles"]
            target:
                working: ["FF", "C", "O"]
                not_working: ["S", "IE"]
