#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    extension:
        notifications:
            enable: false 
            name: Notifications
            twitter:
              enable: false
              consumer_key: app_consumer_key
              consumer_secret: app_consumer_secret
              oauth_token: your_oauth_token_for_this_app
              oauth_token_secret: your_oauth_token_secret_for_this_app
              target_username: 
            email:
              enable: false
              from_address: sender_email_address
              to_address: receipient_email_address
              smtp_host: 127.0.0.1
              smtp_port: 25
