#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
################################################################################
# For more information see: http://itsecuritysolutions.org/2012-08-12-WANem-v2.3-multiple-vulnerabilities/
################################################################################
beef:
    module:
        wanem_command_execution:
            enable: true
            category: "Exploits"
            name: "WAN Emulator Command Execution"
            description: "Attempts to get a reverse root shell on a WAN Emulator server.<br/>Tested on version 2.3 however other versions are likely to be vulnerable."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
