#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#

beef:
    module:
        get_physical_location:
            enable: true
            category: "Host"
            name: "Get Physical Location"
            description: "This module will retrieve geolocation information based on the neighboring wireless access points using commands encapsulated within a signed Java Applet. <br/><br/>The details will include:<br/> <ul><li> - GPS Coordinates details</li><li> - Street Address details</li></ul><br/><br/> If the victim machine has a firewall that monitors outgoing connections (Zonealaram, LittleSnitch, ..), calls to Google maps will be alerted."
            authors: ["keith_lee @keith55 http://milo2012.wordpress.com", "antisnatchor"]
            target:
                working: ["IE"]
                user_notify: ["C", "S", "O", "FF"]
