#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
#  local_file_theft
#
#  Shamelessly plagurised from kos.io/xsspwn

beef:
    module:
        local_file_theft:
            enable: true
            category: "Misc"
            name: "Local File Theft"
            description: "JavaScript may have filesystem access if we are running from a local resource and using the file:// scheme.<br/>This module checks common locations and cheekily snaches anything it finds. Shamelessly plagurised from http://kos.io/xsspwn. To test this module save the BeEF hook page locally and open in Safari from the your localfile system."
            authors: ["mh"]
            target:
                working: ["S"]
