#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        actiontec_q1000_csrf:
            enable: true
            category: ["Exploits", "Router"]
            name: "Actiontec Q1000 CSRF"
            description: "Attempts to enable remote web and telnet administration, and disables the firewall on an Actiontec Q1000 router."
            authors: ["james-otten"]
            target:
                working: ["ALL"]
