#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        popunder_window:
            enable: true
            category: "Persistence"
            name: "Create Pop Under"
            description: "This module creates a new discrete pop under window with the BeEF hook included.<br><br>Another browser node will be added to the hooked browser tree."
            authors: ["ethicalhack3r"]
            target:
                user_notify: ["ALL"]
