#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
################################################################################
# For more information see: http://support.freenas.org/ticket/1788
################################################################################
beef:
    module:
        freenas_reverse_root_shell_csrf:
            enable: true
            category: ["Exploits", "NAS"]
            name: "FreeNAS Reverse Root Shell CSRF"
            description: "Attempts to get a reverse root shell on a FreeNAS server.<br/>Tested on version 8.2.0 however other versions are likely to be vulnerable.<br/>Patched in version 8.3.0-BETA3."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
