#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        detect_cups:
            enable: true
            category: "Host"
            name: "Detect CUPS"
            description: "This module attempts to detect Common UNIX Printing System (CUPS) on localhost on the default port 631."
            authors: ["bcoles"]
            target:
                working:
                    ALL:
                        os: ["Linux"]
                not_working:
                    ALL:
                        os: ["All"]
