#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        google_search:
            enable: true
            category: "Misc"
            name: "Google Search"
            description: "This module uses the hooked browser to search Google."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
