#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        sqlitemanager_xss:
            enable: true
            category: ["Exploits", "XSS"]
            name: "SQLiteManager XSS"
            description: "Attempts to hook SQLiteManager using XSS.<br/>Tested on version 1.2.4 however other versions are likely to be vulnerable."
            authors: ["bcoles"]
            target:
                unknown: ["ALL"]
