#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        get_all_cookies:
            enable: true
            category: "Chrome Extensions"
            name: "Get All Cookies"
            description: "Steal cookies, even HttpOnly cookies, providing the hooked extension has cookies access.<br />If a URL is not specified then <em>all</em> cookies are returned (this can be a lot!)"
            authors: ["mh"]
            target:
                working: ["C"]
                not_working: ["All"]
