#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    extension:
        evasion:
            enable: true
            name: 'Evasion'
            authors: ["antisnatchor"]
            exclude_core_js: ["lib/jquery-1.5.2.min.js", "lib/json2.js", "lib/jools.min.js", "lib/mdetect.js"]
            scramble_variables: true
            scramble_cookies: true
            scramble:
              beef: "beef"
              Beef: "Beef"
              evercookie: "evercookie"
            chain: ["scramble", "minify", "base_64", "whitespace"]
