#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        get_registry_keys:
            enable: true
            category: "Host"
            name: "Get Registry Keys"
            description: "Retrieves the values of Windows Registry keys using an (unsafe) ActiveX control. Internet Explorer does NOT allow scripting of unsafe ActiveX controls in the Internet zone by default.<br /><br />Note: Each registry key must be placed on a new line."
            authors: ["bcoles"]
            target:
                user_notify: ["IE"]
                not_working: ["ALL"]
